DeadlyBossMods/DBM-Classic

DBM-Party-Classic/DBM-Party-Classic.toc

Add zhCN index

---

DBM-Party-Classic/DBM-Party-Classic.toc
DBM-Party-Classic/Scholomance/DarkmasterGandling.lua
DBM-Party-Classic/Scholomance/DoctorTheolenKrastinov.lua
DBM-Party-Classic/Scholomance/InstructorMalicia.lua
DBM-Party-Classic/Scholomance/JandiceBarov.lua
DBM-Party-Classic/Scholomance/KirtonostheHerald.lua
DBM-Party-Classic/Scholomance/LadyIlluciaBarov.lua
DBM-Party-Classic/Scholomance/LordAlexeiBarov.lua
DBM-Party-Classic/Scholomance/LorekeeperPolkelt.lua
DBM-Party-Classic/Scholomance/MardukBlackpool.lua
DBM-Party-Classic/Scholomance/RasFrostwhisper.lua
DBM-Party-Classic/Scholomance/Rattlegore.lua
DBM-Party-Classic/Scholomance/TheRavenian.lua
DBM-Party-Classic/Scholomance/Vectus.lua
DBM-Party-Classic/localization.en.lua

This contains no timers but adds basic boss tracking to Scholomance. Locales for English language only.
Tested in-game and working as expected.

Add basic boss tracking to Scholomance

---

DBM-Party-Classic/DBM-Party-Classic.toc
DBM-Party-Classic/UpperBlackrockSpire/GeneralDrakkisath.lua
DBM-Party-Classic/UpperBlackrockSpire/GoralukAnvilcrack.lua
DBM-Party-Classic/UpperBlackrockSpire/Gyth.lua
DBM-Party-Classic/UpperBlackrockSpire/JedRunewatcher.lua
DBM-Party-Classic/UpperBlackrockSpire/PyroguardEmberseer.lua
DBM-Party-Classic/UpperBlackrockSpire/SolakarFlamewreath.lua
DBM-Party-Classic/UpperBlackrockSpire/TheBeast.lua
DBM-Party-Classic/UpperBlackrockSpire/WarchiefRendBlackhand.lua
DBM-Party-Classic/localization.en.lua

Basic combat detection with English locales.

Basic boss tracking for UBRS

---

DBM-AQ20/DBM-AQ20.toc
DBM-AQ40/DBM-AQ40.toc
DBM-BWL/DBM-BWL.toc
DBM-DefaultSkin/DBM-DefaultSkin.toc
DBM-MC/DBM-MC.toc
DBM-Naxx/DBM-Naxx.toc
DBM-Party-Classic/DBM-Party-Classic.toc
DBM-Party-Classic/localization.es.lua
DBM-StatusBarTimers/DBM-StatusBarTimers.toc
DBM-ZG/DBM-ZG.toc

Added esMX to titles for modules, updated spanish with scholomance for party-classic

updated spanish localization

---

DBM-GUI/DBM-GUI_Templates.xml

Add **DBM_GUI_OptionsFrame** to **UISpecialFrames** to have it ride on UIParent CloseSpecialWindows()

Close GUI with escape key, closes #52

---

DBM-BWL/Chromaggus.lua
DBM-BWL/localization.en.lua

Chromaggus: add vulnerability cd timer

---

DBM-BWL/localization.tw.lua

update some event can't work on zh-TW client duo to string does not match
Nefarian class call
Chromaggus spell weakness

update localization.tw.lua v1.1

---

DBM-BWL/Chromaggus.lua
DBM-BWL/DBM-BWL.toc
DBM-BWL/Vulnerability.lua
DBM-BWL/localization.en.lua

BWL: Add vulnerability warnings for chromag and trash

---

DBM-BWL/Razorgore.lua
DBM-BWL/localization.cn.lua
DBM-BWL/localization.de.lua
DBM-BWL/localization.en.lua
DBM-BWL/localization.es.lua
DBM-BWL/localization.kr.lua
DBM-BWL/localization.ru.lua
DBM-BWL/localization.tw.lua

No options, no sync, just the basics.

[WIP] Razorgore Egg Counter

---

DBM-Party-Classic/Stratholme/RamsteintheGorger.lua
DBM-Party-Classic/localization.en.lua

This change is something I've been wanting to do for myself for the longest time. I hope the quality is good enough to please the master 😇

Add timer for black guards after Ramstein death

---

DBM-Core/DBM-Core.lua

ish-hacky way of doing it, but I mean, least it supports locale, and there's not a better method I can see?

Support locale for WBE, WBD, GCB, GCE

---

DBM-Core/DBM-Core.lua

This one was missed in 7dd10e0e3157c688d19df5ec1e50857893848c53

Update WBA sync for whisperSyncHandlers for version 4

---

DBM-Core/DBM-Core.lua

These works out more memory efficient.

Sync retail change for strFromTime

---

DBM-AQ20/AQ20Trash.lua
DBM-AQ20/DBM-AQ20.toc
DBM-AQ20/localization.cn.lua
DBM-AQ20/localization.de.lua
DBM-AQ20/localization.en.lua
DBM-AQ20/localization.es.lua
DBM-AQ20/localization.kr.lua
DBM-AQ20/localization.ru.lua
DBM-AQ20/localization.tw.lua
DBM-AQ40/AQ40Trash.lua

AQ: add reflect/plague warnings for anubisath trash

---

DBM-AQ40/Fankriss.lua

aq/fankriss: add entangle warning and yell

---

DBM-AQ40/CThun.lua

aq/cthun: remove dark glare cd for phase 2

---

DBM-AQ40/ThreeBugs.lua

aq/threebugs: add toxin to gtfo warnings

---

DBM-AQ40/Viscidus.lua

aq/visc: add toxin gtfo warning

---

DBM-AQ20/AQ20Trash.lua
DBM-AQ40/AQ40Trash.lua

aq/trash: add warning for cause insanity / mind control

---

DBM-BWL/Chromaggus.lua
DBM-BWL/Flamegor.lua

Send boss name with the BWL enrage warnings

---

DBM-AQ20/Buru.lua
DBM-AQ20/Kurinnaxx.lua
DBM-AQ40/Fankriss.lua
DBM-AQ40/Huhuran.lua
DBM-AQ40/Ouro.lua
DBM-AQ40/TwinEmps.lua
DBM-Azeroth/Emeriss.lua
DBM-Azeroth/Lethon.lua
DBM-Azeroth/Taerar.lua
DBM-Azeroth/Ysondre.lua
DBM-BWL/Broodlord.lua
DBM-BWL/Chromaggus.lua
DBM-BWL/Ebonroc.lua
DBM-BWL/Flamegor.lua
DBM-BWL/Vaelastrasz.lua
DBM-MC/Magmadar.lua
DBM-MC/Shazzrah.lua
DBM-MC/Sulfuron.lua
DBM-Onyxia/Onyxia.lua
DBM-Party-Classic/Gnomeregan/CrowdPummeler.lua
DBM-Party-Classic/Gnomeregan/Electrocutioner6000.lua
DBM-Party-Classic/RagefireChasm/Taragaman.lua
DBM-Party-Classic/Stratholme/MagistrateBarthilas.lua
DBM-Party-Classic/Stratholme/Narubenkan.lua
DBM-Party-Classic/Uldaman/Ironaya.lua
DBM-ZG/Bloodlord.lua

and show flame breath to heals for onyxia
#461 #466

bump all of the tank option versions

---

DBM-Core/DBM-Core.lua

core: add tank to arms/ret spec role and check for tank stance in IsTank

---

DBM-AQ40/CThun.lua
DBM-AQ40/localization.cn.lua
DBM-AQ40/localization.en.lua

I had test it. (based on 1.13.56, not the newest one)

Tentacle Spawn Timer

---

DBM-AQ40/CThun.lua

#460 #332 
needs some more testing, but at least this won't error on unit_health now

cthun/tentacle: fixup a couple errors, still not exposing infoframe

---

DBM-Party-Classic/UpperBlackrockSpire/PyroguardEmberseer.lua

For better localization support in DBM-Party-Classic\UBRS

Support partial string find on Pyroguard Emberseer pull

---

DBM-AQ40/CThun.lua

Spawn time Update, and we all forgot timerWeakened

---

DBM-Naxx/ArachnidQuarter/Anub'Rekhan.lua
DBM-Naxx/ArachnidQuarter/Faerlina.lua
DBM-Naxx/ArachnidQuarter/Maexxna.lua
DBM-Naxx/ConstructQuarter/Gluth.lua
DBM-Naxx/MilitaryQuarter/Horsemen.lua
DBM-Naxx/MilitaryQuarter/Razuvious.lua
DBM-Naxx/PlagueQuarter/Loatheb.lua
DBM-Naxx/PlagueQuarter/Noth.lua

from aggregating ptr warcraftlogs, you could see the timer stats in the below if you want to do this differently
https://gist.github.com/venuatu/a9f2b4310d86bbb1f07534555271c2f6

naxx: refine some timers from logs

---

DBM-Naxx/ArachnidQuarter/Maexxna.lua

naxx/maexxna: add web wrap timer

---

DBM-Naxx/MilitaryQuarter/Horsemen.lua

Accidental copy/paste from Holy Wrath? 😊
Spell ID is correct everywhere else.

Spell ID typo for Four Horsemen Shield Wall

---

DBM-Naxx/ArachnidQuarter/Faerlina.lua
DBM-Naxx/ArachnidQuarter/Maexxna.lua
DBM-Naxx/MilitaryQuarter/Razuvious.lua

Naxx: Remove invalid Wrath spells

---

DBM-Naxx/MilitaryQuarter/Horsemen.lua

Classic spell has the same name as the player Shield Wall.

Naxx-4H: Prevent shield wall trigger from players

---

DBM-Naxx/FrostwyrmLair/Kel'Thuzad.lua

I saw that a weakaura was giving out personal warnings for this and what do you know, this actually targets someone

naxx/kt: Add fissure yell and include target

---

DBM-Core/DBM-Core.lua

Correction to commit 34d3c03d4ddeba38db49aebd65c985cc57820a7e

Message prefix typo from retail sync

---

DBM-GUI/modules/options/timers/Behavior.lua
DBM-StatusBarTimers/DBT.lua

Sort feature is a bit more descriptive
Fix x-offset

More DBT fixes (Retail sync)

---

DBM-Naxx/PlagueQuarter/Loatheb.lua

More Accurate Loatheb doom timer (Fixes #713)

---

DBM-Core/DBM-RangeCheck.lua

The range of 43 item doesn't exist.

Fix range frame 43 value
